STATIONS = [
    "Warszawa Centralna",
    "Kraków Główny",
    "Wrocław Główny",
    "Gdańsk Główny",
    "Poznań Główny",
    "Łódź Fabryczna",
    "Katowice",
    "Szczecin Główny",
    "Bydgoszcz Główna",
    "Lublin",
    "Zielona Góra",
    "Toruń Główny",
    "Rzeszów Główny",
    "Olsztyn Główny",
    "Gdynia Główna",
    "Białystok",
    "Kielce",
    "Opole Główne",
    "Częstochowa Główna",
    "Nowy Sącz",
]
